const mongoose=require("mongoose")
const userSchema=mongoose.Schema({
    full_name:{
        type:String,
    },
    wavelength_id:{
        type:String,
    },
    phone:{
        type:String,
    },
    profile_pic:{
        type:String,
    },
    email:{
        type:String,
    },
    password:{
        type:String,
    },
    address:{
        type:String,
    },
    course:{
        type:String,
        enum:['B.Sc.CSIT','BCA','CMAT','BIT','BE'],
    },
    role:{
        type:String,
        enum:['super_admin','admin','moderator','mentor','student'],
        default:"student"
    },
    is_active:{
        type:Boolean,
        default:true
    },
    is_admitted:{
        type:Boolean,
        default:false
    },
    is_verified:{
        type:Boolean,
        default:false
    },
    last_paid_date:{
        type:Date
    },
    paid_amount:{
        type:String,
    },
    refered_by:{
        type:String,
    },
    refer_id:{
        type:String
    },
    refer_points:{
        type:String
    }
},{
    timestamps:true,
    autoIndex:true,
    autoCreate:true
});

const User=mongoose.model("User",userSchema);
module.exports=User;
