const router = require("express").Router()
const body_parser = require("body-parser")
const { addMCQ, addManyMCQ, listAllMcqs, mcqCheck, fetchMcqs } = require("../controllers/mcq.controller")
const parser = body_parser.json()
const uploader = require('../middlewares/uploader.middleware')
router.route("/mcq/add")
    .post(parser,uploader.single('image'),addMCQ)
router.route("/mcq/addmany")
    .post(parser,uploader.single('image'),addManyMCQ)
router.route("/mcq/listall")
    .get(listAllMcqs)
router.route("/mcq/fetch")
    .post(parser,uploader.single('image'),fetchMcqs)
router.route("/mcq/check")
    .post(parser,mcqCheck)

module.exports = router