const router = require("express").Router()
const body_parser = require("body-parser")
const parser = body_parser.json()
const { addTest, updateTest, listTests, showTest, deleteTest } = require("../controllers/test.controller")
const { isLoggedIn } = require("../middlewares/logincheck.middleware")
const uploader = require('../middlewares/uploader.middleware')
router.route('/test/add')
    .post(isLoggedIn,parser,uploader.single('image'),addTest)
router.route('/test/update/:id')
    .put(isLoggedIn,parser,updateTest)
router.route('/test/listall')
    .get(isLoggedIn,listTests)
router.route('/test/fetch/:id')
    .get(isLoggedIn,showTest)
router.route('/test/delete/:id')
    .delete(isLoggedIn,deleteTest)

module.exports = router